### PR TITLE
Add server power state and current usage

### PR DESCRIPTION
**Pull request by ErdbeerbaerLP**
I added the ability to get power states and the ram/cpu/hdd usage of the server.

Closes https://github.com/stanjg/Ptero4J/issues/5

### CODE REVIEW

**Comment by stanjg** [comment]
Hi! First of all, thank you for taking the time to contribute to this project.

Your PR looks fine, I do have a couple of requests for changes though.

Please refrain from making any API calls from the UserServer class, this is what the controllers are for. I also don’t want the ‘makeApiCall’ in the UserServersController class being public.

I think it would also be great if we would return a POJO for the server resources instead of an array, to increase the ease of use of this library.

I’d like to hear your thoughts on this.

**Comment by ErdbeerbaerLP** [comment]
> I think it would also be great if we would return a POJO for the server resources instead of an array, to increase the ease of use of this library.

I think that is an better idea instead of an array, did not think about that

**Comment by ErdbeerbaerLP** [comment]
> Please refrain from making any API calls from the UserServer class, this is what the controllers are for. I also don’t want the ‘makeApiCall’ in the UserServersController class being public.

~I think it is working, let me test~ Yes it works

**Comment by stanjg** [comment]
Thank you for your pull request, it has now been merged into the master branch.

**Pull request merged**
